### ISSUE TITLE
httpclient version pinned to insecure version

### ISSUE THREAD

**Issue by wouterh** [iconara/etcd-rb#19]
The version specified for httpclient pins httpclient to 2.3.x. httpclient < 2.4.0 pins the SSL/TLS protocol to SSLv3, which is considered broken. This has been replaced by version negotiation by OpenSSL in v2.4.0:
https://github.com/nahi/httpclient/commit/1753454f5d2c45d34f72eb52b456216ce4a95774

I will try to submit a pull request today that loosen the version constraint to 2.x. That should also fix #18

**Comment by luispollo** [comment]
@wouterh Thanks for the heads-up. It looks like there was already a pending PR that addressed the issue with the version of httpclient (#16) so I just merged that. I'm not currently using etcd-rb, so it'd be great if you could confirm this does the trick.

**Comment by wouterh** [comment]
That'll probably work, but now the version is pinned to 2.8.x which unnecessarily limits compatibility with other gems. etcd-rb is known to work with versions equal to or higher than 2.3, so setting the dependency to '~>2.3' would be better. That would allow anything higher than 2.3.0, but lower than 3.0.

**Comment by luispollo** [comment]
Makes sense. Feel free to submit a new PR to loosen the version.

2017-05-08 8:14 GMT-05:00 Wouter Horré <notifications@github.com>:
